services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authservice-prod
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      # Render DB (same as dev)
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d5f0kpngi27c73cdr31g-a.singapore-postgres.render.com:5432/authdb_1pab?sslmode=require
      SPRING_DATASOURCE_USERNAME: jack
      SPRING_DATASOURCE_PASSWORD: NjrbPgx5jhQQ5m300lliubF3y4nxoPRw
