services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authservice
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src

        - action: rebuild
          path: pom.xml
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
